// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service.proto

package demo.server;

public final class DemoServiceProto {
  private DemoServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_server_DemoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_server_DemoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_server_DemoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_server_DemoReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022demo_service.proto\022\013demo.server\"\033\n\013Dem" +
      "oRequest\022\014\n\004name\030\001 \001(\t\"\034\n\tDemoReply\022\017\n\007m" +
      "essage\030\001 \001(\t2M\n\013DemoService\022>\n\010SayHello\022" +
      "\030.demo.server.DemoRequest\032\026.demo.server." +
      "DemoReply\"\000B!\n\013demo.serverB\020DemoServiceP" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_demo_server_DemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_server_DemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_server_DemoRequest_descriptor,
        new String[] { "Name", });
    internal_static_demo_server_DemoReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_server_DemoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_server_DemoReply_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
