// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_service.proto

package demo.server;

public interface DemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demo.server.DemoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
