spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: calis@123
    driver-class-name: com.mysql.jdbc.Driver


# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.kuaishou.qa.example.mouse.entity    # 实体类所在的位置