package com.kuaishou.qa.example.mouse.mapper;

import com.kuaishou.qa.example.mouse.entity.User;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Fri Jul 16 11:52:26 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Fri Jul 16 11:52:26 CST 2021
     */
    int insert(User record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Fri Jul 16 11:52:26 CST 2021
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Fri Jul 16 11:52:26 CST 2021
     */
    int updateByPrimaryKey(User record);
}